### ISSUE TITLE
Reevaluate output based on input updates

### ISSUE THREAD

**Issue by ftonato** [ftonato/svelte-debugger#4]
https://github.com/sveltejs/svelte/issues/2636#issuecomment-630292399

**Comment by FSou1** [comment]
Here is a demo: https://svelte.dev/repl/a0a83312f5ff4bd6bbc6fc8e855db514?version=3.6.7

**Comment by ftonato** [comment]
@FSou1 It must be working :)

**Comment by ftonato** [comment]
**Note:** I need to update npm version before close this issue...

**Comment by ftonato** [comment]
https://www.npmjs.com/package/svelte-debugger/v/1.0.4
----
Hey @FSou1, sorry for my delay, from now on everything should work if you update the package to the latest version.

Thanks again @eliamartani o/
